name: Deploy to Plesk

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload static site to Plesk (FTP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          timeout: 120000
          local-dir: ./
          server-dir: /energiepa.snarfia.nl/
          exclude: |
            **/data/**
            **/.git*
            **/.github/**
            **/.pycache/**
            **/server.py
            **/server.js
            **/scripts/**
            **/README.md
